name: Run Worker Threads with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-workers:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Instala as dependências
      - name: Install dependencies
        run: npm install

      # Instala os navegadores Playwright
      - name: Install Playwright browsers
        run: npx playwright install

      # Executa o script com xvfb-run
      - name: Run script with xvfb
        run: xvfb-run --auto-servernum -- node main.js
