name: Set Up Node.js Project with Playwright

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Create project directory and initialize npm
        run: |
          mkdir novo-projeto
          cd novo-projeto
          npm init -y
          jq '. + {"type": "module"}' package.json > tmp.json && mv tmp.json package.json

      - name: Copy main.js to novo-projeto
        run: |
          cp main.js novo-projeto/

      - name: Rename main.js to main.mjs
        run: |
          mv novo-projeto/main.js novo-projeto/main.js

      - name: Install Playwright
        run: |
          cd novo-projeto
          npm install playwright

      - name: Install Playwright system dependencies
        run: |
          sudo npx playwright install-deps

      - name: Install Axios and Node-Fetch
        run: |
          cd novo-projeto
          npm install axios node-fetch

      - name: Install Playwright Browsers
        run: |
          cd novo-projeto
          npx playwright install

      - name: Run script with Playwright (headed)
        run: |
          cd novo-projeto
          xvfb-run --auto-servernum -- node main.js
