name: Set Up Node.js Project with Puppeteer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-puppeteer:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Cria o diretório novo-projeto e inicializa npm
      - name: Create project directory and initialize npm
        run: |
          mkdir novo-projeto
          cd novo-projeto
          npm init -y
          jq '. + {"type": "module"}' package.json > tmp.json && mv tmp.json package.json

      # Copia o arquivo main.js para o novo diretório
      - name: Copy main.js to novo-projeto
        run: |
          cp main.js novo-projeto/

      # Renomeia main.js para main.mjs
      - name: Rename main.js to main.mjs
        run: |
          mv novo-projeto/main.js novo-projeto/main.mjs

      # Instala o Puppeteer
      - name: Install Puppeteer
        run: |
          cd novo-projeto
          npm install puppeteer

      # Executa o script com Puppeteer
      - name: Run script with Puppeteer
        run: |
          cd novo-projeto
          node main.mjs
