name: Run Worker Threads

on:
  push:
    branches:
      - mai
  pull_request:
    branches:
      - main

jobs:
  run-workers:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Altere para a versão necessária

      # Instala as dependências (se houver um package.json)
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      # Executa o script principal
      - name: Run main script
        run: node main.js
